name: Build and Push Prod Images

on:
  workflow_call:
    inputs:
      version_tag:
        description: "Version tag for the release (e.g., v1.0.0)"
        required: true
        type: string

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build-and-push-arbiter-prod:
    name: Build and Push Arbiter Image
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-jfrog.yaml@v2.0.0
    with:
      repo_name: kyoto-oci-local-prod
      image_name: agentarena-arbiter
      platforms: "linux/amd64"
      ignore_trivy: false
      run_trivy: true
      context: ./Demo
      dockerfile_path: ./Demo/Dockerfile
      additional_tags: ${{ inputs.version_tag }}
      docker_build_args: |
        GITHUB_SHA=${{ github.sha }}
      push: true
